version: '3.1'
services:
  web:
    build:
      context: ..
      dockerfile: Dockerfile
    image: php:7.4-apache
    container_name: php74sand
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: keksdb


  adminer:
    image: adminer
    restart: always
    ports:
      - 3306:8080